### ISSUE TITLE
How to connect to Hasura Cloud

### ISSUE THREAD

**Issue by arthuryeti** [ghoshnirmalya/nextjs-hasura-boilerplate#28]
Hey @ghoshnirmalya!

Such a nice project and would love to contribute.

I'm trying to use Hasura Cloud instead of the dockerized backend. Do you know how to do it?

**Comment by ghoshnirmalya** [comment]
Hi @arthuryeti,

Thank you for the kind words. I haven't used Hasura Cloud. So, I'm not completely sure how to integrate that. However, the front-end (Next.js) application only needs to know the back-end API and the database url. So, if you modify the values in the env file ([which you'll need to do as a part of this step while bootstrapping the project](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate#3-create-a-env-file-and-copy-the-contents-from-envexample-present-in-frontend-directory)), it should work fine.

Let me know if this helps. If it works, I'd be grateful if you can add it to the [readme.md](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate/blob/master/readme.md) file.

**Comment by tsega** [comment]
I was looking for this exact same thing. I've already configured my Hasura Cloud with the JWT public key and the boilerplate app is able to connect to my Hasura Cloud instance, however,  when setting the database option in `[...nextauth].ts` the authentication fails with the following error:

```
[next-auth][error][adapter_connection_error] error: no pg_hba.conf entry for host "xxx.xxx.xx.xx", user "xxxxxxxx", database "xxxxxxx", SSL off
    at Parser.parseErrorMessage (nextjs-hasura-boilerplate/frontend/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/nextjs-hasura-boilerplate/frontend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/nextjs-hasura-boilerplate/frontend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/nextjs-hasura-boilerplate/frontend/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

If this works, I'll be more than happy to update the README.md file with how to connect to Hasura Cloud.

**Comment by tsega** [comment]
Additionally when, I remove the database option. I'm able to login but since the app has no access to the database, my user info is not saved and functionality of the app, like viewing ones profile is not possible.

**Comment by ghoshnirmalya** [comment]
@tsega Can you please try adding `?sslmode=require` to [`NEXT_PUBLIC_DATABASE_URL`](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate/blob/master/frontend/.env.example#L3) (`postgres://postgres:@localhost:5432/postgres?sslmode=require`)?

**Comment by arnaudjnn** [comment]
Having exactly the same error. If I ass ssl=true I have:

```
error: self signed certificate
```

I don't know where to allow the IP as detailes here: https://hasura.io/docs/1.0/graphql/cloud/projects/create.html#allowing-connections-from-hasura-cloud-ip

**Comment by arnaudjnn** [comment]
I added the following config to the database configuration object and it works.

```
ssl: true,
    extra: {
      ssl: {
        rejectUnauthorized: false
      },
    },
```

I don't know if it's the correct way to do

**Comment by ghoshnirmalya** [comment]
We've added this as the [default configuration](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate/blob/master/frontend/pages/api/auth/%5B...nextauth%5D.ts#L18-L31).
