### ISSUE TITLE
how to update Hasura?

### ISSUE THREAD

**Issue by oldo** [ghoshnirmalya/nextjs-hasura-boilerplate#301]
Hi there,
Great boilerplate, thank you!
I'm trying to update Hasura to the latest version `hasura/graphql-engine:v2.0.0-alpha.6` however when I set `image` in `docker-compose.yml` and `FROM` in `DOCKERFILE` accordingly, the server still reports it is on v1.3.3.
I must be missing something simple here?
Thanks.

**Comment by ghoshnirmalya** [comment]
You need to update [this line](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate/blob/master/backend/Dockerfile#L1) to **hasura/graphql-engine:v2.0.0-alpha.6.cli-migrations-v2**.

**Comment by oldo** [comment]
You're a legend, thanks @ghoshnirmalya
