### ISSUE TITLE
How secure is to define database env variable with prefix `NEXT_PUBLIC_`? 

### ISSUE THREAD

**Issue by Param-Harrison** [ghoshnirmalya/nextjs-hasura-boilerplate#66]
Exposing sensitive values to the browser is not a good idea.
I believe database value is only used on API routes. In that case, those are purely backend serverless functions. We don't need to provide a `NEXT_PUBLIC_` prefix if it is just used directly from the backend.

You can check more details here.
https://nextjs.org/docs/basic-features/environment-variables

**Comment by ghoshnirmalya** [comment]
`NEXT_PUBLIC_DATABASE_URL` is used in the [nextauth.ts](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate/blob/7661db3b7096ca1902a883893ac2453a4194ab44/frontend/pages/api/auth/%5B...nextauth%5D.ts#L18) file. It's used only on API routes. I'll check whether NextAuth will work if we don't provide the credentials on the client side.

**Comment by Param-Harrison** [comment]
@ghoshnirmalya 👍 
the API folder inside the pages folder is special in the next Js context. it will be server-side only. 
You can check the details here man.
https://nextjs.org/docs/api-routes/introduction

From the docs,
> Any file inside the folder pages/api is mapped to /api/* and will be treated as an API endpoint instead of a page. They are server-side only bundles and won't increase your client-side bundle size.

**Comment by ghoshnirmalya** [comment]
> @ghoshnirmalya 👍
> the API folder inside the pages folder is special in the next Js context. it will be server-side only.
> You can check the details here man.
> https://nextjs.org/docs/api-routes/introduction
> 
> From the docs,
> 
> > Any file inside the folder pages/api is mapped to /api/* and will be treated as an API endpoint instead of a page. They are server-side only bundles and won't increase your client-side bundle size.

@Param-Harrison Thank you. Can you please create a PR for that?

**Comment by Param-Harrison** [comment]
Sure @ghoshnirmalya 👍

**Comment by ghoshnirmalya** [comment]
Resolved in [0.3.4](https://github.com/ghoshnirmalya/nextjs-hasura-boilerplate/releases/tag/0.3.4).
