### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by mil0sh** [ghoshnirmalya/nextjs-hasura-boilerplate#67]
Hi, Thank you for great project.

I was wondering how to set up user roles in this project.
Now it seems that the roles are hardcoded in JWT claims.

"https://hasura.io/jwt/claims": {
  "x-hasura-allowed-roles": ["admin", "user"],
  "x-hasura-default-role": "user",
   "x-hasura-role": "user",
  "x-hasura-user-id": token.id,
}

**Comment by ghoshnirmalya** [comment]
@mil0sh You're correct. Right now, the roles are hard-coded in JWT claims. I agree that there should be a setup which will allow developers to setup user roles. I plan to work on it soon.

**Comment by mil0sh** [comment]
Thank you for your reply.

I have managed to create a quick fix by creating field role in users table with default value "user", and then get the value while JWT and session are created.

Not the most elegant solution, but it works for now.
